using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;
using HousecarlCore;
using HousecarlMcp;

namespace HousecarlGenerator;

/// <summary>
/// REGRESSION GUARD (standing CI instrument) for the verify-loop wave (HCBR-2026-06-11-02, Aaron-decided Option A:
/// NO off-disk read of disabled plugins — the loop closes via honest errors + write-time read-back instead):
///
///   (a) ERROR TAXONOMY — a `plugin=` read naming a plugin that is NOT in the load order must say exactly that
///       (and point at the working verify paths), NEVER the false "Plugin 'X' does not define {fk} (it does not
///       touch this record)". That falsehood reads as "my write was lost" and invites re-issuing the ops —
///       duplicate list Adds into the patch (the report's bite). The true does-not-define message stays for the
///       in-order-but-doesn't-define case ONLY.
///
///   (b) WRITE-TIME FULL READ-BACK (wishlist #3, re-scoped 2026-06-08) — the write cleave's opt-in fullReadback
///       returns every touched/created record IN FULL, re-read from the WRITTEN FILE on disk (the same bytes MO2
///       will load), so a write is verifiable BEFORE the patch is enabled — including the report's headline
///       payload, a composed perk-gate condition (the compose grammar from the report's Positive finding).
///
/// Self-contained, in the pattern of <c>snapshot-view-guard</c> / <c>writelock-guard</c>: synthesizes a 2-plugin
/// order ON DISK (a master with weapons + a perk + a COBJ; an override plugin touching ONE weapon), drives the
/// REAL <see cref="LoadOrderService.ResolveRead"/> (ForGuard seam) for the taxonomy arms and the REAL
/// <see cref="WritePatchBuilder.Apply"/>/<see cref="WritePatchBuilder.CreateRecords"/> for the read-back arms
/// (rulebook generated BY CONSTRUCTION in-process — no checked-in corpus, no game data).
///
/// RED before the wave's (a) fix on the taxonomy-miss arms (the old message claimed "does not define");
/// the does-not-define CONTROL and the read-back arms hold GREEN on the fixed code.
///
/// Run: <c>dotnet run --project src/housecarl-generator -- verify-loop-guard</c>
/// </summary>
internal static class VerifyLoopProbe
{
    static int _pass, _fail;

    public static int RunGuard(string[] args)
    {
        Console.WriteLine("################  REGRESSION GUARD — verify-loop wave: plugin= miss taxonomy + write-time full read-back (HCBR-2026-06-11-02)  ################");
        Console.WriteLine();

        var dir = Path.Combine(Path.GetTempPath(), "hc_verify_loop_guard");
        try { if (Directory.Exists(dir)) Directory.Delete(dir, recursive: true); } catch { }
        Directory.CreateDirectory(dir);

        const string masterName = "hcVerifyMaster.esp", ovrName = "hcVerifyOvr.esp", ghostName = "hcVerifyGhost.esp";
        var masterPath = Path.Combine(dir, masterName);
        var ovrPath = Path.Combine(dir, ovrName);

        try
        {
            // ---- 1. MASTER: weapons W1 (named, damage 10) + W2, a gate perk, and a bare COBJ. Masterless (CI
            //         has no game files). W1's Name is the never-edited field the full read-back must still show. ----
            var master = new SkyrimMod(ModKey.FromNameAndExtension(masterName), SkyrimRelease.SkyrimSE);
            var w1 = master.Weapons.AddNew(); w1.EditorID = "hcVerifyW1"; w1.Name = "Verify Weapon One";
            w1.BasicStats = new WeaponBasicStats { Damage = 10 };
            var w2 = master.Weapons.AddNew(); w2.EditorID = "hcVerifyW2";
            var perk = master.Perks.AddNew(); perk.EditorID = "hcVerifyGatePerk";
            var cobj = master.ConstructibleObjects.AddNew(); cobj.EditorID = "hcVerifyRecipe";
            FormKey w1Fk = w1.FormKey, w2Fk = w2.FormKey, perkFk = perk.FormKey, cobjFk = cobj.FormKey;
            master.BeginWrite.ToPath(masterPath).WithLoadOrder(Array.Empty<ISkyrimModGetter>()).Write();

            // ---- 2. OVERRIDE: touches W1 ONLY — so it is the in-order plugin that genuinely does NOT define W2
            //         (the control case whose message must stay). ----
            var ovr = new SkyrimMod(ModKey.FromNameAndExtension(ovrName), SkyrimRelease.SkyrimSE);
            WriteEngine.GenericGetOrAddAsOverride(ovr, w1);
            ovr.BeginWrite.ToPath(ovrPath).WithLoadOrder(new ISkyrimModGetter[] { master }).Write();

            using var resolver = LoadOrderResolver.Build(new[] { masterPath, ovrPath });
            var svc = LoadOrderService.ForGuard(resolver, new UserConfigStore(Path.Combine(dir, "houseCARL.user.json")));
            Console.WriteLine($"-- built order {masterName} < {ovrName} (override touches W1 only); '{ghostName}' exists nowhere --");
            Console.WriteLine();

            // ============ (a) ERROR TAXONOMY — the REAL service ResolveRead ============
            var miss = svc.ResolveRead(w1Fk, ghostName, null, conflictTree: false);
            Check("TAXONOMY MISS: plugin= naming a not-in-order plugin FAILS (no silent winner fallback)",
                  miss.Error is not null);
            Check("TAXONOMY MISS: the error names the TRUE condition ('not in the load order')",
                  miss.Error is not null && miss.Error.Contains("not in the load order", StringComparison.OrdinalIgnoreCase));
            Check("TAXONOMY MISS: the error NEVER claims the plugin 'does not define' the record (the false message that invites duplicate re-writes)",
                  miss.Error is not null && !miss.Error.Contains("does not define", StringComparison.OrdinalIgnoreCase));
            Check("TAXONOMY MISS: the error points at the pre-enable verify path (full_readback) — actionable, not a dead end",
                  miss.Error is not null && miss.Error.Contains("full_readback", StringComparison.OrdinalIgnoreCase));

            var noDefine = svc.ResolveRead(w2Fk, ovrName, null, conflictTree: false);
            Check("TAXONOMY CONTROL: an IN-ORDER plugin that doesn't define the record keeps the true does-not-define message",
                  noDefine.Error is not null
                  && noDefine.Error.Contains("does not define", StringComparison.OrdinalIgnoreCase)
                  && noDefine.Error.Contains("does not touch this record", StringComparison.OrdinalIgnoreCase));

            var defines = svc.ResolveRead(w1Fk, ovrName, null, conflictTree: false);
            Check("TAXONOMY CONTROL: an in-order plugin that DOES define the record still reads clean (source = the named plugin)",
                  defines.Error is null && string.Equals(defines.SourcePlugin, ovrName, StringComparison.OrdinalIgnoreCase));
            Console.WriteLine();

            // ============ (b) WRITE-TIME FULL READ-BACK — the REAL write cleave ============
            var rulebook = CorpusRulebook.Load(GenerateCorpus(dir));
            var patchPath = Path.Combine(dir, "hcVerifyPatch.esp");

            // The report's exact workflow: a scalar edit + a composed perk-gate condition (Add ConditionFloat,
            // then Set Conditions[0].Data via compose — the Positive-finding grammar), into a patch that is NOT
            // in the load order. fullReadback must hand back BOTH whole records off the written file.
            var edits = new WritePatchBuilder.PatchEdit[]
            {
                new() { Target = w1Fk, Path = new[] { "BasicStats", "Damage" }, Verb = "Set", Value = "777" },
                new() { Target = cobjFk, Path = new[] { "Conditions" }, Verb = "Add",
                        Struct = new StructSpec
                        {
                            Type = "ConditionFloat",
                            Fields = new Dictionary<string, string> { ["CompareOperator"] = "EqualTo", ["ComparisonValue"] = "1" },
                        } },
                new() { Target = cobjFk, Path = new[] { "Conditions[0]", "Data" }, Verb = "Set",
                        Struct = new StructSpec
                        {
                            Type = "HasPerkConditionData",
                            Sets = new List<WriteRequest>
                            {
                                new() { RecordType = "HasPerkConditionData", Path = new[] { "Perk" }, Verb = "Set", Value = perkFk.ToString() },
                            },
                        } },
            };
            var applied = WritePatchBuilder.Apply(resolver, rulebook, edits, patchPath, extend: false, fullReadback: true);
            Check($"READBACK: Apply succeeded (scalar edit + composed perk-gate condition)  [{applied.Error ?? "ok"}]",
                  applied.Success);
            Check("READBACK: ReadBack present with BOTH touched records (de-duped: 3 ops -> 2 records), no per-record errors",
                  applied.ReadBack is { Count: 2 } && applied.ReadBack.All(r => r.Error is null && r.Record is not null));

            var w1Back = applied.ReadBack?.FirstOrDefault(r => r.Record?.FormKey == w1Fk.ToString())?.Record;
            Check("READBACK: the edited leaf shows the NEW value (BasicStats.Damage = 777) — read from the file on disk",
                  w1Back is not null && w1Back.Fields.Any(f =>
                      f.Path.Contains("Damage", StringComparison.OrdinalIgnoreCase) && f.HasValue && f.Token == "777"));
            Check("READBACK: a field the call NEVER touched is still there intact (Name = 'Verify Weapon One') — the WHOLE record, not just the edited leaves",
                  w1Back is not null && w1Back.Fields.Any(f =>
                      f.Path == "Name" && f.HasValue && (f.Token ?? "").Contains("Verify Weapon One")));

            var cobjBack = applied.ReadBack?.FirstOrDefault(r => r.Record?.FormKey == cobjFk.ToString())?.Record;
            Check("READBACK: the written perk gate is verifiable PRE-ENABLE — the COBJ read-back surfaces Conditions content referencing the gate perk",
                  cobjBack is not null && cobjBack.Fields.Any(f =>
                      f.Path.StartsWith("Conditions", StringComparison.OrdinalIgnoreCase)
                      && ((f.Token ?? "") + (f.Note ?? "")).Contains(perkFk.ToString(), StringComparison.OrdinalIgnoreCase)));

            // Ground truth, independent of the read-back: re-open the written file raw and assert the condition landed.
            Check("GROUND TRUTH: the written file carries the HasPerk gate on the COBJ (raw Mutagen re-open agrees with the read-back)",
                  WrittenCobjHasPerkGate(patchPath, cobjFk, perkFk));

            var silent = WritePatchBuilder.Apply(resolver, rulebook,
                new[] { new WritePatchBuilder.PatchEdit { Target = w1Fk, Path = new[] { "BasicStats", "Damage" }, Verb = "Set", Value = "778" } },
                patchPath, extend: true);
            Check("READBACK CONTROL: without fullReadback the outcome carries NO ReadBack (opt-in — no surprise token cost)",
                  silent.Success && silent.ReadBack is null);

            var createOut = WritePatchBuilder.CreateRecords(resolver, rulebook,
                new[] { new WritePatchBuilder.CreateSpec { RecordType = "Keyword", EditorId = "HcVerifyKw", Edits = Array.Empty<WriteRequest>() } },
                Path.Combine(dir, "hcVerifyCreate.esp"), extend: false, fullReadback: true);
            Check($"READBACK CREATE: CreateRecords with fullReadback hands back the new record in full (editorid HcVerifyKw)  [{createOut.Error ?? "ok"}]",
                  createOut.Success && createOut.ReadBack is { Count: 1 } crb
                  && crb[0].Error is null && crb[0].Record is { } cr && cr.EditorId == "HcVerifyKw");

            Console.WriteLine();
            Console.WriteLine($"=== verify-loop-guard: {_pass} passed, {_fail} failed -> {(_fail == 0 ? "PASS" : "FAIL")} ===");
            return _fail == 0 ? 0 : 1;
        }
        catch (Exception ex) { Console.WriteLine($"   FAIL (unexpected): {ex.GetType().Name}: {ex.Message}"); return 1; }
        finally { try { Directory.Delete(dir, recursive: true); } catch { } }
    }

    // Generate the validator corpus BY CONSTRUCTION (reflect the linked Mutagen assembly) into the temp dir — the
    // same self-contained posture as writelock-guard: no checked-in corpus.json, no game data, just slower.
    static string GenerateCorpus(string dir)
    {
        var genDir = Path.Combine(dir, "corpus-gen");
        CorpusGenerator.GenerateAll(genDir, Path.Combine(dir, "corpus-ref"));
        return Path.Combine(genDir, "corpus.json");
    }

    static bool WrittenCobjHasPerkGate(string path, FormKey cobjFk, FormKey perkFk)
    {
        ISkyrimModGetter? ov = null;
        try
        {
            ov = SkyrimMod.CreateFromBinaryOverlay(path, SkyrimRelease.SkyrimSE);
            var c = ov.ConstructibleObjects.FirstOrDefault(x => x.FormKey == cobjFk);
            return c is not null && c.Conditions.Count == 1
                && c.Conditions[0].Data is IHasPerkConditionDataGetter hp
                && WriteEngine.ReadFloiFormKey(hp.Perk) == perkFk;   // the oracle-proven FLOI accessor (.Link on the overlay)
        }
        catch { return false; }
        finally { (ov as IDisposable)?.Dispose(); }
    }

    static void Check(string label, bool ok)
    {
        Console.WriteLine($"   [{(ok ? "PASS" : "FAIL")}] {label}");
        if (ok) _pass++; else _fail++;
    }
}
