using System.Text.Json;
using System.Text.RegularExpressions;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Pex;

namespace HousecarlCore;

/// <summary>
/// Builds the decompiler's child→parent class map. The map feeds implicit-UPCAST suppression in
/// <see cref="PapyrusDecompiler"/> — a SOFT dependency by construction: a missing or partial map
/// means the output keeps explicit casts (correct, compilable, gate-tier cosmetic only — never
/// wrong code), so every loader here degrades to "fewer edges", never to a throw.
///
/// Three sources, layered by the caller (the service caches the merged map for process lifetime):
///   1. the committed baseline (vanilla-class-parents.json, generated by construction from the CK
///      vanilla sources' own ScriptName-extends headers; ships beside the exe),
///   2. loose .psc headers across Amethyst staging mods that ship sources,
///   3. the input .pex itself + its sibling .pex files (every pex declares its own parent).
/// </summary>
public static class PapyrusClassParents
{
    static readonly Regex ExtendsRx = new(@"^\s*ScriptName\s+(\S+)\s+extends\s+(\S+)",
        RegexOptions.IgnoreCase | RegexOptions.Compiled);

    /// <summary>Load the committed baseline. Missing/corrupt file → empty map + a reason string the
    /// caller surfaces in the tool result (Q3: the degraded mode is named, never silent).</summary>
    public static (Dictionary<string, string> Edges, string? Note) LoadBaseline(string jsonPath)
    {
        var edges = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        if (!File.Exists(jsonPath))
            return (edges, $"baseline class hierarchy not found beside the server ({Path.GetFileName(jsonPath)}) — output keeps explicit casts");
        try
        {
            using var doc = JsonDocument.Parse(File.ReadAllText(jsonPath));
            foreach (var p in doc.RootElement.GetProperty("edges").EnumerateObject())
                if (p.Value.GetString() is { Length: > 0 } parent) edges.TryAdd(p.Name, parent);
            return (edges, null);
        }
        catch (Exception ex)
        {
            return (new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase),
                    $"baseline class hierarchy unreadable ({ex.GetType().Name}) — output keeps explicit casts");
        }
    }

    /// <summary>Top up from `ScriptName X extends Y` headers of loose .psc files under
    /// <paramref name="roots"/> (cheap line reads; the scrape the bulk gate proved at 25,919-edge
    /// scale). First edge per child wins. Returns the number of edges added.</summary>
    public static int AddFromPscHeaders(Dictionary<string, string> edges, IEnumerable<string> roots)
    {
        int added = 0;
        foreach (var root in roots)
        {
            if (!Directory.Exists(root)) continue;
            IEnumerable<string> files;
            try
            {
                files = Directory.EnumerateFiles(root, "*.psc",
                    new EnumerationOptions { RecurseSubdirectories = true, IgnoreInaccessible = true });
            }
            catch { continue; }
            foreach (var f in files)
            {
                try
                {
                    foreach (var line in File.ReadLines(f).Take(20))
                    {
                        var m = ExtendsRx.Match(line);
                        if (!m.Success) continue;
                        if (edges.TryAdd(m.Groups[1].Value, m.Groups[2].Value)) added++;
                        break;
                    }
                }
                catch { /* unreadable psc — fewer edges, never fatal */ }
            }
        }
        return added;
    }

    /// <summary>Top up from a parsed pex's own object→parent declarations.</summary>
    public static int AddFromPex(Dictionary<string, string> edges, PexFile pex)
    {
        int added = 0;
        foreach (var obj in pex.Objects)
            if (obj.Name is { Length: > 0 } name && obj.ParentClassName is { Length: > 0 } parent
                && edges.TryAdd(name, parent)) added++;
        return added;
    }

    /// <summary>Top up from every readable .pex in <paramref name="folder"/> (non-recursive — the
    /// input's own siblings; a mod's scripts folder is flat). Unreadable pex = skipped, fewer edges.</summary>
    public static int AddFromPexFolder(Dictionary<string, string> edges, string folder)
    {
        int added = 0;
        if (!Directory.Exists(folder)) return 0;
        foreach (var f in Directory.EnumerateFiles(folder, "*.pex"))
        {
            try { added += AddFromPex(edges, PexFile.CreateFromFile(f, GameCategory.Skyrim)); }
            catch { /* the known unreadable class — fewer edges, never fatal */ }
        }
        return added;
    }
}
